apiVersion: v2
name: openclaw
description: A Helm chart for deploying OpenClaw - an open-source AI personal assistant
type: application
version: 0.1.4
appVersion: "2026.2.1"
keywords:
  - openclaw
  - ai
  - assistant
  - llm
home: https://openclaw.ai
sources:
  - https://github.com/openclaw/openclaw
maintainers:
  - name: Chris
